[config]
default_to_workspace = false
skip_core_tasks = true

[env]
RUST_BACKTRACE = 0

[tasks.format]
command = "cargo"
args = ["fmt"]

[tasks.format-check]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.check]
command = "cargo"
args = ["check"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.docs]
command = "cargo"
args = ["doc", "--open", "--no-deps"]

[tasks.unit]
command = "cargo"
args = ["test", "--lib", "--", "--nocapture"]

[tasks.integration]
command = "cargo"
args = ["test"]

[tasks.test]
dependencies = ["unit", "integration"]

[tasks.dev]
dependencies = ["check-wasm", "test", "format", "clippy"]

[tasks.check-wasm]
command = "cargo"
args = ["check", "--target", "wasm32-unknown-unknown"]

[tasks.clean-profraw]
script = '''
rm -f *.profraw
'''

[tasks.clean-coverage]
script = '''
rm -rf ./target/llvm-cov
'''
dependencies = ["clean-profraw"]

[tasks.coverage]
script = '''
cargo llvm-cov clean
cargo llvm-cov test
cargo llvm-cov report --html
'''

[tasks.cover]
dependencies = ["clean-coverage", "coverage", "clean-profraw"]
