use thiserror::Error;

/// Errors generated by the vCard library.
#[derive(Debug, Error)]
pub enum Error {
    #[error("input token was expected but reached EOF")]
    TokenExpected,

    #[error("input token was incorrect")]
    IncorrectToken,

    #[error("property name '{0}' is not supported")]
    UnknownPropertyName(String),

    #[error("property value is invalid")]
    InvalidPropertyValue,
}
